name: Keep CloudType Server Alive

on:
  schedule:
    # 매 3분마다 실행 (UTC 기준) - Vercel Cron과 겹치지 않게
    - cron: '*/3 * * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  ping-server:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Backend Server
        run: |
          echo "🤖 Starting keep-alive ping..."
          
          # 백엔드 서버 핑
          for i in {1..3}; do
            echo "Attempt $i: Pinging backend..."
            if curl -f -s --max-time 30 https://port-0-seat-management-mcdii4ecc60f3aad.sel5.cloudtype.app/api/seats; then
              echo "✅ Backend is alive!"
              break
            else
              echo "❌ Backend ping failed, retrying in 10 seconds..."
              sleep 10
            fi
          done
          
      - name: Ping Frontend Server  
        run: |
          echo "🌐 Pinging frontend..."
          
          # 프론트엔드 서버 핑
          for i in {1..2}; do
            echo "Attempt $i: Pinging frontend..."
            if curl -f -s --max-time 20 https://seat-management-el5wgnzgi-jaeho-chois-projects.vercel.app; then
              echo "✅ Frontend is alive!"
              break
            else
              echo "❌ Frontend ping failed, retrying in 5 seconds..."
              sleep 5
            fi
          done
          
      - name: Health Check API
        run: |
          echo "🏥 Testing API endpoints..."
          
          # 주요 API 엔드포인트 체크
          curl -f -s --max-time 20 https://port-0-seat-management-mcdii4ecc60f3aad.sel5.cloudtype.app/api/timeslots || echo "Timeslots API might be sleeping"
          
          echo "✨ Keep-alive ping completed at $(date)" 